### PR TITLE
re-usable dataset select component

### LINKED ISSUE #1220: Line Analysis crashes when opened with no data loaded
**Reporter:** pllim

Workflow to reproduce:

1. Display Specviz but do not load any data.
2. Open Line Analysis plugin.
3. See traceback that appears under viewer.

```
.../jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py in _on_plugin_opened_changed(self, *args)
    148             # default to first entry in list instead of leaving empty.
    149             # by placing this logic here, we avoid running on app/data load.
--> 150             self.selected_spectrum = self.dc_items[0]
    151 
    152     @property

IndexError: list index out of range
```

[🐱](https://jira.stsci.edu/browse/JDAT-2290)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements a re-usable dataset select component with:
* entry-filtering (some cases only want 1d spectra, only spectra in the current mosviz row, excluding output from model fitting plugin, etc).
* automatic hiding when only one entry (by default - this can be disabled)
* default selection to first entry
* convenience functionality to access the selected Spectrum1D or data-collection objects from within the plugin.

This also creates a new `BaseSelectPluginComponent` which holds shared logic between the `DatasetSelect`, `ViewerSelect` (#1195), and `SubsetSelect` (#1156, #1175).

Finally, this splits the spatial subsets into their own dropdown in model fitting.  For cubeviz this will effectively _replace_ the data dropdown since the data dropdown is hidden as it is only populated with a single choice (unless more data is manually added).

Below are some before (left) & after (right) screenshots:

<div>
mosviz metadata before
mosviz metadata after
</div>

<div>
cubeviz fitting before

cubeviz fitting after
</div>

Fixes #1220

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [x] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [x] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [x] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [x] Did the CI pass? If not, are the failures related?
- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`?
- [x] Is a milestone set?
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

File: jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue [hunk 1]
```diff
@@ -36,8 +34,9 @@
     <v-row>
       <v-text-field
         ref="n_moment"
+        type="number"
         label="Moment"
-        v-model="n_moment"
+        v-model.number="n_moment"
```
Comment (kecnry) [inline jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.vue:39]: fixed this while I was here... using `.number` along with `IntHandleEmpty` removes the need for error handling in the plugin.

File: jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py [hunk 2]
```diff
@@ -43,48 +40,30 @@ class GaussianSmooth(TemplateMixin):
...
-        self.hub.subscribe(self, DataCollectionAddMessage,
-                           handler=self._on_data_updated)
-        self.hub.subscribe(self, DataCollectionDeleteMessage,
-                           handler=self._on_data_updated)
-
-        self._selected_data = None
         if self.config == "cubeviz":
             self.show_modes = True
+            # retrieve the data from the cube, not the collapsed 1d spectrum
+            self.dataset._viewer_refs = ['flux-viewer', 'spectrum-viewer']
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/gaussian_smooth/gaussian_smooth.py:46]: this feels a little hacky - is it worth generalizing more or exposing a more friendly method to do this?

File: jdaviz/configs/default/plugins/line_lists/line_lists.py [hunk 3]
```diff
@@ -377,7 +377,7 @@ def _auto_slider_range(self, event=None):
         # by taking abs, this will work for wavelength or frequency units.
         half_range = abs(x_max - x_min) / x_mid
         ndec = -np.log10(half_range)
-        if ndec > 0:
+        if ndec > 0 and not np.isinf(ndec):
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/line_lists/line_lists.py:380]: ran into a traceback when testing and clearing all data from the viewer (range goes to zero, ndec goes to infinity)

File: jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py [hunk 4]
```diff
@@ -15,30 +16,32 @@ def test_view_dict(imviz_helper):
     imviz_helper.load_data(ndd_1, data_label='has_simple_meta')
     imviz_helper.load_data(ndd_2, data_label='has_nested_meta')
     imviz_helper.load_data(arr, data_label='no_meta')
-    assert mv.dc_items == ['has_simple_meta[DATA]', 'has_nested_meta[DATA]', 'no_meta']
+    assert mv.dataset.labels == ['has_simple_meta[DATA]', 'has_nested_meta[DATA]']
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: entries without metadata are filtered out by the `DatasetSelect` component now

File: jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py [hunk 5]
```diff
@@ -342,7 +292,7 @@ def _uncertainty(result):
                 # TODO: update specutils to be consistent with region vs regions and default to
                 # regions=None so this elif can be removed
                 temp_result = FUNCTIONS[function](spec_subtracted, region=None)
-                self.results_centroid = temp_result.to_value(u.AA)
+                self.results_centroid = temp_result.to_value(u.AA, equivalencies=u.spectral())
```
Comment (kecnry) [inline jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py:295]: ran into a bug when testing when the spectrum was in frequencies

File: jdaviz/configs/specviz/tests/test_helper.py [hunk 6]
```diff
@@ -257,12 +258,12 @@ def test_plot_uncertainties(specviz_helper, spectrum1d):
...
 
     specviz_viewer.show_uncertainties()
 
-    assert len(specviz_viewer.figure.marks) == 2
+    assert len([m for m in specviz_viewer.figure.marks if isinstance(m, LineUncertainties)]) == 1
 
     specviz_viewer.clean()
 
-    assert len(specviz_viewer.figure.marks) == 1
+    assert len([m for m in specviz_viewer.figure.marks if isinstance(m, LineUncertainties)]) == 0
```
Comment (kecnry) [inline jdaviz/configs/specviz/tests/test_helper.py:269]: changed this since the LineAnalysis plugin might add (hidden) marks, so let's just check against the ones we expect for uncertainties.

File: jdaviz/core/template_mixin.py [hunk 7]
```diff
@@ -286,34 +352,16 @@ def _update_subset(self, subset, attribute=None):
...
-    def selected_item(self):
-        for item in self.items:
-            if item['label'] == self.selected:
-                return item
-        return {}
-
     @cached_property
     def selected_obj(self):
-        if self.selected == self._default_text:
+        if self.selected == self._default_text or self.selected not in self.labels:
```
Comment (kecnry) [inline jdaviz/core/template_mixin.py:364]: this is needed since this could be triggered by an observer in a plugin WHILE an error is raised on an invalid selection and before the default can be applied

**Review by pllim — COMMENTED** [review]
In the Moment Map plugin, I dunno how I feel about "Spectral Region" dropdown not appearing until there is a spectral subset created. At first I thought it was a bug and got confused. Also, I use that dropdown to remind me that I can actually create moment map with Subset. Without that dropdown to remind me, I won't get reminded until I create a Subset, which I might not. Maybe that's just me? 🤷

File: jdaviz/core/template_mixin.py [hunk 8]
```diff
@@ -608,3 +644,185 @@ class ViewerSelectMixin(VuetifyTemplate, HubListener):
     def __init__(self, *args, **kwargs):
         super().__init__(*args, **kwargs)
         self.viewer = ViewerSelect(self, 'viewer_items', 'viewer_selected')
+
+
+class DatasetSelect(BaseSelectPluginComponent):
+    """
+    Traitlets (in the object, custom traitlets in the plugin):
+
+    * ``items`` (list of dicts with keys: )
```
Comment (rosteen) [inline jdaviz/core/template_mixin.py:653]: Is there supposed to be something after the colon here?

**Comment by kecnry** [comment]
> I dunno how I feel about "Spectral Region" dropdown not appearing until there is a spectral subset created.

I did this in a number of places, but it is easily changed by setting `show_if_single_entry="true"` in the template.  Alternatively, especially for subsets, we could have the dropdown replaced with text explaining how to add a subset etc if there are no subsets?

**Comment by rosteen** [comment]
+1 from me for keeping the subset dropdowns visible even if there are currently none as a reminder that subsets could be applied to the operations in the plugin.

**Review by rosteen — COMMENTED** [review]
Looks pretty good, other than agreeing with @pllim's comment as I said already. The filter logic made enough sense for me to see how it's used, but I'm definitely adding that to my mental list of "things that should be explained in the developer docs." I'm going to hold off on approving until the subset selection default behavior is updated.

**Comment by kecnry** [comment]
I changed it so that all subset dropdowns are always visible (and dataset dropdowns are always visible in mosviz, since I think its important to give some indication of the change as you change rows).

File: jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py [hunk 9]
```diff
@@ -91,8 +58,8 @@ def vue_calculate_moment(self, *args):
         # Need transpose to align JWST mirror shape. Not sure why.
         self.moment = CCDData(analysis.moment(slab, order=n_moment).T)
 
-        label = "Moment {}: {}".format(n_moment, self._selected_data.label)
-        fname_label = self._selected_data.label.replace("[", "_").replace("]", "")
+        label = "Moment {}: {}".format(n_moment, self.dataset_selected)
```
[the remark this answers is not in the document]
Comment (pllim) [reply jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py:61]: Oh no... I can see where this is going... type annotations! 👻 

p.s. While you are at this, might as well change `format.()` to f-string?

[the remark this answers is not in the document]
Comment (rosteen) [reply jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py:61]: Oh yeah, good call on the f-strings, didn't even register in my brain when I looked at it.

[the remark this answers is not in the document]
Comment (kecnry) [reply jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py:61]: I agree with you, and that's probably why it used to always be `selected_`.  But I thought it was worth the change to be self consistent with a prefix.  

I'll explain here just so that there is a paper trail, and we can think about adding some of this into the dev docs somewhere.  Each component/mixin adds an attribute to the plugin to access the component itself while keeping the traitlets at the plugin-level so they're accessible to observe and use in the templates.  So for dataset, there is a `plugin.dataset` which points to the underlying dataset component object.  This means that you can access the traitlets directly as `plugin.dataset_selected` but also could access them with `plugin.dataset.selected`... and that's why I went with a common "component-name-prefix" convention, even if its a bit less intuitive linguistically. 🤷

File: jdaviz/components/plugin_dataset_select.vue [hunk 10]
```diff
@@ -0,0 +1,45 @@
...
+        <span>
+          {{ data.item.label }}
+        </span>
+      </div>
+    </template>
+   </v-select>
+  </v-row>
+ </div>
+</template>
+<script>
```
[the remark this answers is not in the document]
Comment (kecnry) [reply jdaviz/components/plugin_dataset_select.vue:33]: You can do a lot in the exports, but here the `props` are the properties/arguments that are accepted when calling the template component from another template.

File: jdaviz/core/template_mixin.py (hunk 8 above)
Comment (kecnry) [reply jdaviz/core/template_mixin.py]: good catch, thanks! (added in the latest commit)

File: jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py (hunk 9 above)
[the remark this answers is not in the document]
Comment (rosteen) [reply jdaviz/configs/cubeviz/plugins/moment_maps/moment_maps.py:61]: Really I think either order of the words could have either connotation, so since there's a good reason for it this way I'm cool with it.

**Comment by pllim** [comment]
"Plot all" of SDSS lines on Cubeviz example notebook seems very slow but I can't tell if it is related to this refactoring or not.

**Comment by kecnry** [comment]
> "Plot all" of SDSS lines on Cubeviz example notebook seems very slow but I can't tell if it is related to this refactoring or not.

That was never optimized (only redshift sliding with a lot of lines was optimized), I see no reason why this PR would affect that, but if you see it slower than in main let me know and I'll investigate!

**Comment by pllim** [comment]
> if you see it slower than in main

No, I do not. I got confused with Specviz, as it loads fast in Specviz but not Cubeviz. Same behavior in `main`.

**Review by rosteen — APPROVED** [review]
I give it a 15% chance that a scientist will be able to break the data selection somehow, but I wasn't able to in the testing I did. I still would prefer f-strings to using `.format` as @pllim said, but I'm approving since that's not critical by any means.

File: jdaviz/configs/default/plugins/model_fitting/model_fitting.py [hunk 11]
```diff
@@ -32,18 +33,13 @@ def __init__(self, value, unit=None):
...
 @tray_registry('g-model-fitting', label="Model Fitting")
-class ModelFitting(PluginTemplateMixin, SpectralSubsetSelectMixin):
+class ModelFitting(PluginTemplateMixin, DatasetSelectMixin, SpectralSubsetSelectMixin):
     dialog = Bool(False).tag(sync=True)
     template_file = __file__, "model_fitting.vue"
-    dc_items = List([]).tag(sync=True)
-    form_valid_data_selection = Bool(False).tag(sync=True)
     form_valid_model_component = Bool(False).tag(sync=True)
 
-    selected_data = Unicode("").tag(sync=True)
```
Comment (javerbukh) [inline jdaviz/configs/default/plugins/model_fitting/model_fitting.py:42]: There are still lines in this file (428 to 431) that use `self.selected_data` and that caused an error for me when doing model fitting.

Comment (kecnry) [reply jdaviz/configs/default/plugins/model_fitting/model_fitting.py:42]: woah, good catch!  I swear I tested cube fitting... no idea why that didn't show up.  I now did a fully text-search and there are no other remaining `self.selected_data` instances.

**Comment by javerbukh** [comment]
So I did run into an error where if I add the SDSS Line Lists and remove them (click the big X button), I get a `ValueError: Could not remove row 3 from index` traceback which originates here:
```
File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/default/plugins/line_lists/line_lists.py:774, in LineListTool.vue_remove_list(self, listname)
    770 self.list_contents = {k: v for k, v in self.list_contents.items() if k != listname}
    771 row_inds = [i for i, ln in
    772             enumerate(self._viewer.spectral_lines['listname'])
    773             if ln == listname]
--> 774 self._viewer.spectral_lines.remove_rows(row_inds)
```
I assume this bug is outside the scope of this PR since I don't think the line_lists.py file was altered at all but I figured I'd bring it up in case they are related.

**Comment by rosteen** [comment]
> I assume this bug is outside the scope of this PR since I don't think the line_lists.py file was altered at all but I figured I'd bring it up in case they are related.

I hadn't run into this since I always just erase the lines, not remove the list, but I confirmed that it's present outside of this PR as well.

**Review by javerbukh — APPROVED** [review]
Tried every configuration and plugin and everything seems to function as expected. Great work!

**Comment by javerbukh** [comment]
@rosteen I'll open a ticket for that.
@pllim do you or any POs (@camipacifici @PatrickOgle @orifox @larrybradley ) want to do another review on this before it gets merged?

**Comment by pllim** [comment]
Re: https://github.com/spacetelescope/jdaviz/pull/1221#issuecomment-1087889779 -- I thought I opened issue about that at #1168 but now I also see #1228 . 

Yes, I am going through Imviz for this PR. I will approve when that checks out.

**Comment by javerbukh** [comment]
@pllim My bad! Should've search first, I'll delete mine and reference yours.

**Review by pllim — CHANGES_REQUESTED** [review]
Metadata, Simple Aperture Photometry, and Layer Options plugins are unusable when I have no data selected in `imviz-0` but there is data shown in `imviz-1`.

File: jdaviz/core/template_mixin.py [hunk 12]
```diff
@@ -122,16 +131,125 @@ def app(self):
...
+                d['reference'] = viewer_item['reference']
+                d['label'] = viewer_item['reference']
+            else:
+                d['reference'] = None
+                d['label'] = viewer_item['id']
+            return d
+
+        return [_dict_from_viewer(viewer, self.app._viewer_item_by_id(vid))
+                for vid, viewer in self.app._viewer_store.items()
+                if viewer.__class__.__name__ != 'MosvizTableViewer']
```
Comment (pllim) [inline jdaviz/core/template_mixin.py:148]: Would we ever want to subclass `MosvizTableViewer`? If so, `isinstance` is safer maybe?

```suggestion
                if not isinstance(viewer, MosvizTableViewer)
```

**Comment by javerbukh** [comment]
Going off of @pllim's review, I do see another weird interaction.
1) Start Imviz example notebook
2) Create new viewer
3) Open plot options
4) De-select data from imviz-0
5) Select data in imviz-1
6) Look at plot options for imviz-1

There should be nothing showing in the drop down for layer options and a traceback in the console.

<details>
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/ipyvue/VueTemplateWidget.py:60, in Events._handle_event(self, _, content, buffers)
     58     getattr(self, "vue_" + event)(data, buffers)
     59 else:
---> 60     getattr(self, "vue_" + event)(data)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/app.py:1117, in Application.vue_data_item_selected(self, event)
   1113 else:
   1114     selected_items = list(filter(
   1115         lambda id: id != item_id, viewer_item['selected_data_items']))
-> 1117 self._update_selected_data_items(viewer_id, selected_items)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/app.py:1162, in Application._update_selected_data_items(self, viewer_id, selected_items)
   1157     viewer.add_data(data)
   1159     add_data_message = AddDataMessage(data, viewer,
   1160                                       viewer_id=viewer_id,
   1161                                       sender=self)
-> 1162     self.hub.broadcast(add_data_message)
   1164 # Remove any deselected data objects from viewer
   1165 viewer_data = [layer_state.layer
   1166                for layer_state in viewer.state.layers
   1167                if hasattr(layer_state, 'layer') and
   1168                isinstance(layer_state.layer, BaseData)]

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/glue/core/hub.py:215, in Hub.broadcast(self, message)
    213 logging.getLogger(__name__).info("Broadcasting %s", message)
    214 for subscriber, handler in self._find_handlers(message):
--> 215     handler(message)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/core/template_mixin.py:795, in DatasetSelect._on_data_changed(self, msg)
    790 def _on_data_changed(self, msg=None):
    791     # NOTE: _on_data_changed is passed without a msg object during init
    792     # future improvement: don't recreate the entire list when msg is passed
    793     self.items = [{"label": data.label} for data in self.app.data_collection
    794                   if self._is_valid_item(data)]
--> 795     self._apply_default_selection()
    796     # future improvement: only clear cache if the selected data entry was changed?
    797     self._clear_cache(*self._cached_properties)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/core/template_mixin.py:235, in BaseSelectPluginComponent._apply_default_selection(self)
    232     return
    234 if self.default_mode == 'first':
--> 235     self.selected = self.labels[0] if len(self.labels) else ''
    236 elif self.default_mode == 'default_text':
    237     self.selected = self._default_text if self._default_text else ''

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/core/template_mixin.py:111, in BasePluginComponent.__setattr__(self, attr, value, force_super)
    108 if attr[0] == '_' or force_super or attr not in self._plugin_traitlets.keys():
    109     return super().__setattr__(attr, value)
--> 111 return setattr(self._plugin, self._plugin_traitlets.get(attr), value)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/traitlets/traitlets.py:606, in TraitType.__set__(self, obj, value)
    604     raise TraitError('The "%s" trait is read-only.' % self.name)
    605 else:
--> 606     self.set(obj, value)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/traitlets/traitlets.py:595, in TraitType.set(self, obj, value)
    591     silent = False
    592 if silent is not True:
    593     # we explicitly compare silent to True just in case the equality
    594     # comparison above returns something other than True/False
--> 595     obj._notify_trait(self.name, old_value, new_value)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/traitlets/traitlets.py:1219, in HasTraits._notify_trait(self, name, old_value, new_value)
   1218 def _notify_trait(self, name, old_value, new_value):
-> 1219     self.notify_change(Bunch(
   1220         name=name,
   1221         old=old_value,
   1222         new=new_value,
   1223         owner=self,
   1224         type='change',
   1225     ))

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/ipywidgets/widgets/widget.py:686, in Widget.notify_change(self, change)
    683     if name in self.keys and self._should_send_property(name, getattr(self, name)):
    684         # Send new state to front-end
    685         self.send_state(key=name)
--> 686 super(Widget, self).notify_change(change)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/traitlets/traitlets.py:1229, in HasTraits.notify_change(self, change)
   1227 def notify_change(self, change):
   1228     """Notify observers of a change event"""
-> 1229     return self._notify_observers(change)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/traitlets/traitlets.py:1266, in HasTraits._notify_observers(self, event)
   1263 elif isinstance(c, EventHandler) and c.name is not None:
   1264     c = getattr(self, c.name)
-> 1266 c(event)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/configs/default/plugins/metadata_viewer/metadata_viewer.py:23, in MetadataViewer._show_metadata(self, event)
     21 @observe("dataset_selected")
     22 def _show_metadata(self, event):
---> 23     data = self.dataset.selected_obj
     24     if data is None:
     25         self.has_metadata = False

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/functools.py:967, in cached_property.__get__(self, instance, owner)
    965 val = cache.get(self.attrname, _NOT_FOUND)
    966 if val is _NOT_FOUND:
--> 967     val = self.func(instance)
    968     try:
    969         cache[self.attrname] = val

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/core/template_mixin.py:749, in DatasetSelect.selected_obj(self)
    746         return match
    747 # handle the case of empty Application with no viewer, we'll just pull directly
    748 # from the data collection
--> 749 return self.get_object(cls=Spectrum1D)

File ~/Documents/jdaviz_dev/jdaviz/jdaviz/core/template_mixin.py:729, in DatasetSelect.get_object(self, *args, **kwargs)
    726 if self.selected not in self.labels:
    727     # _apply_default_selection will override shortly anyways
    728     return None
--> 729 return self.selected_dc_item.get_object(*args, **kwargs)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/glue/core/data.py:289, in BaseData.get_object(self, cls, **kwargs)
    284         raise ValueError('Specify the object class to use with cls= - supported '
    285                          'classes are:' + format_choices(data_translator.supported_classes))
    287 handler, _ = data_translator.get_handler_for(cls)
--> 289 return handler.to_object(self, **kwargs)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/glue_astronomy/translators/spectrum1d.py:288, in Specutils1DHandler.to_object(self, data_or_subset, attribute, statistic)
    283     return data_kwargs
    285 data_kwargs = parse_attributes(
    286     [attribute] if not hasattr(attribute, '__len__') else attribute)
--> 288 return Spectrum1D(**data_kwargs, **kwargs)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/specutils/spectra/spectrum1d.py:276, in Spectrum1D.__init__(self, flux, spectral_axis, wcs, velocity_convention, rest_value, redshift, radial_velocity, bin_specification, **kwargs)
    271 # If no spectral_axis was provided, create a SpectralCoord based on
    272 # the WCS
    273 if spectral_axis is None:
    274     # If the WCS doesn't have a spectral attribute, we assume it's the
    275     # dummy GWCS we created or a solely spectral WCS
--> 276     if hasattr(self.wcs, "spectral"):
    277         # Handle generated 1D WCS that aren't set to spectral
    278         if not self.wcs.is_spectral and self.wcs.naxis == 1:
    279             spec_axis = self.wcs.pixel_to_world(np.arange(self.flux.shape[-1]))

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/astropy/wcs/wcs.py:3212, in WCS.spectral(self)
   3207 @property
   3208 def spectral(self):
   3209     """
   3210     A copy of the current WCS with only the spectral axes included
   3211     """
-> 3212     return self.sub([WCSSUB_SPECTRAL])

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/astropy/wcs/wcs.py:592, in WCS.sub(self, axes)
    590 def sub(self, axes=None):
--> 592     copy = self.deepcopy()
    594     # We need to know which axes have been dropped, but there is no easy
    595     # way to do this with the .sub function, so instead we assign UUIDs to
    596     # the CNAME parameters in copy.wcs. We can later access the original
    597     # CNAME properties from self.wcs.
    598     cname_uuid = [str(uuid.uuid4()) for i in range(copy.wcs.naxis)]

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/astropy/wcs/wcs.py:588, in WCS.deepcopy(self)
    581 def deepcopy(self):
    582     """
    583     Return a deep copy of the object.
    584 
    585     Convenience method so user doesn't have to import the
    586     :mod:`copy` stdlib module.
    587     """
--> 588     return copy.deepcopy(self)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/copy.py:153, in deepcopy(x, memo, _nil)
    151 copier = getattr(x, "__deepcopy__", None)
    152 if copier is not None:
--> 153     y = copier(memo)
    154 else:
    155     reductor = dispatch_table.get(cls)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/site-packages/astropy/wcs/wcs.py:561, in WCS.__deepcopy__(self, memo)
    556 new_copy = self.__class__()
    557 new_copy.naxis = deepcopy(self.naxis, memo)
    558 WCSBase.__init__(new_copy, deepcopy(self.sip, memo),
    559                  (deepcopy(self.cpdis1, memo),
    560                   deepcopy(self.cpdis2, memo)),
--> 561                  deepcopy(self.wcs, memo),
    562                  (deepcopy(self.det2im1, memo),
    563                   deepcopy(self.det2im2, memo)))
    564 for key, val in self.__dict__.items():
    565     new_copy.__dict__[key] = deepcopy(val, memo)

File ~/opt/anaconda3/envs/dataset_select_dev/lib/python3.8/copy.py:153, in deepcopy(x, memo, _nil)
    151 copier = getattr(x, "__deepcopy__", None)
    152 if copier is not None:
--> 153     y = copier(memo)
    154 else:
    155     reductor = dispatch_table.get(cls)

RuntimeError: NULL error object in wcslib
</details

**Comment by pllim** [comment]
Hmm weird that Metadata Viewer from Imviz would call this:

`--> 749 return self.get_object(cls=Spectrum1D)`

File: jdaviz/core/template_mixin.py (hunk 12 above)
Comment (kecnry) [reply jdaviz/core/template_mixin.py:148]: This would cause a loop in the import statements (I thought I left a comment, but maybe that was in another case of the same thing)

Comment (pllim) [reply jdaviz/core/template_mixin.py:148]: Oh, ok.

File: jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py (hunk 4 above)
Comment (pllim) [reply jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: Will this confuse the users when they don't see it under selection even though they loaded it?

Comment (pllim) [reply jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: Also, this list does not update when metadata is added later (see snippet). I propose we don't try to be too smart here, just list everything and user sees nothing if there is no metadata, as before.

```
import numpy as np
from jdaviz import Imviz

a = np.random.random((10, 10))

imviz = Imviz()
imviz.load_data(a, data_label='test1')
imviz.app

imviz.app.data_collection[0].meta['1'] = 1  # Dropdown still shows nothing
```

Comment (kecnry) [reply jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: I don't think it would be confusing, but we can ask Jenn.  All of the dropdowns now filter to relevant entries, so I see this as consistent with that (it doesn't make much sense to be able to fit a model to a model, etc).  But if we want to show "no metadata for ..." and still include them in the dropdown, I can make that happen.

If updating metadata manually is something we want to support, I can try to support that... but it also was not fully supported before this PR.  Although the entry may have always shown in the dropdown, the displayed metadata would not update if you changed it manually after load, unless possibly if changing the selection.

Comment (pllim) [reply jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: The problem with the notebook workflow is that we cannot predict what user wanna do with this thing. Say, they load data, and then they do some funky processing with it and decide to attach history of said processing as metadata, who are we to deny them?

Should updating metadata trigger display update? Maybe and can be future PR if requested.

Should plugin just not allow showing metadata at all if it is not there on load? I think that is a step backward.

File: jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py (hunk 5 above)
Comment (pllim) [reply jdaviz/configs/specviz/plugins/line_analysis/line_analysis.py:293]: Is this bug out of scope here? If so, is there a follow-up issue?

File: jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py (hunk 4 above)
Comment (kecnry) [reply jdaviz/configs/default/plugins/metadata_viewer/tests/test_metadata_viewer.py:19]: Do we consider accessing and modifying `app.data_collection` as user-facing?  I suspect changing items in the data collection directly will cause issues across the app as we don't listen to changes from there anywhere (aperture photometry, for example, pulls values from metadata when the dropdown changes but won't update in real-time either, etc).  I'm just worried this is a slippery slope.  But if we do want to support user changes to things within data collection, then I would prefer disabling that ability entirely until a full solution is implemented rather than relying on the user to realize the distinction between live-updates and having to toggle a selection to pull the latest values.

I think the decision of whether items without metadata should be excluded or show "no metadata" is independent though, and I don't have a terribly strong opinion except that I always personally prefer self-consistency and showing a message is actually additional logic in the plugin.

**Review by pllim — APPROVED** [review]
I think this is good now, as far as Imviz is concerned. I found a bug in Line Profile but it is also in `main` so I will open a separate issue for that.

**Comment by pllim** [comment]
Thanks!
