### PR TITLE
subset plugin: fallback if unit cannot be found

### LINKED ISSUE #2251: Subset Tools Plugin: Spatial Subset not showing up UI
**Reporter: pllim**

I don't understand what is happening here. The only error I see is in the browser dev console and it points to here:

https://github.com/spacetelescope/jdaviz/blob/2154035e08b1a21f071d202551ec2ac85349d7a5/jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue#L86

`TypeError: Cannot read properties of undefined (reading 'replace')`

Is this a bug introduced by merging the unit conversion branch?

Workflow to reproduce:

1. Fire up Cubeviz or Imviz. Load any data you want. One is enough.
2. Draw a circle Subset on image.
3. Open the Subset Tools plugin.
4. See that nothing is shown even though you would expect the circle parameters to show up. However, the plugin internals get populated properly and I can get the region using `app.get_subsets()` and so on.

I would say this bug is critical and would block a release.

[🐱](https://jira.stsci.edu/browse/JDAT-3506)

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by kecnry**
### Description

This pull request implements a fallback in the subset plugin UI that attempts to display the subset parameters with units (as of #2127) when those units are not available (as in imviz currently).  Since this has not been released yet, it should not require a change log entry.

Fixes #2251

### Change log entry

- [x] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue [hunk 1]
```diff
@@ -83,7 +83,7 @@
           v-model.number="item.value"
           type="number"
           style="padding-top: 0px; margin-top: 0px"
-          :suffix="item.unit.replace('Angstrom', 'A')"
+          :suffix="item.unit ? item.unit.replace('Angstrom', 'A') : ''"
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:86]: in short: if `item.unit` exists, parse it and show the string (shortening "Angstrom" to "A" since unfortunately unicode is not supported, otherwise don’t show a unit at all.

**Review by pllim — APPROVED** [review]
Works again. Thanks for the quick fix!

p.s. Unfortunate about lack of unicode support. "A" could be misinterpreted as "ampere" and so on.

**Comment by kecnry** [comment]
> p.s. Unfortunate about lack of unicode support. "A" could be misinterpreted as "ampere" and so on.

If this is a concern, we can display the unit outside the suffix and use the unicode &#8491; (`&#8491`) - as is currently done elsewhere (like in model fitting).  But I think for now this at least fixes the bug and we can decide on a self-consistent way to show those as we iterate further.

**Review by rosteen — APPROVED** [review]

**Comment by pllim** [comment]
Grrr `HTTP Error 500: Internal Server Error`

**Comment by pllim** [comment]
I'll give it one more chance before I YOLO merge.
