### PR TITLE
Subset Plugin updated to use get_subsets method

### LINKED ISSUE #2068: Subset Tools plugin incorrect after using "remove selection" mode
**Reporter: Jesse Averbukh**

In specviz example notebook, create a spectral subset then use the "remove selection" mode at the top to remove a chunk out of the middle. The Subset Tools plugin shows incorrect values for the range of the subset.

 --- 

 DISCLAIMER: This issue was autocreated by the Jdaviz Issue Creation Bot on behalf of the reporter. If any information is incorrect, please contact [Duy Nguyen](https://github.com/duytnguyendtn)

### PR DESCRIPTION
**Pull request by javerbukh**
### Description

This pull request is to implement `app.get_subsets()` in the Subset Plugin. Still to do:

- [x] Put the region dimensions into a column
- [x] ~~Stop the plugin refreshing multiple times~~ Make ticket for this: #2161 
- [x] Add tests
- [x] Remove debug statements
- [x] Add video demo
- [ ] Add simplify button (stretch)
- [ ] Allow updating of composite subset bounds (stretch)

Video showing repeated plugin refreshing when trying to sync (the UI moving with the plugin tray did not appear in the recording for some reason):

https://user-images.githubusercontent.com/7179333/233375541-9b949f44-6178-42c4-abda-75fb2e7dd4d6.mov

Fixes #2068 

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by javerbukh** [comment]
As far as I can tell, the behavior mentioned here:

>  Stop the plugin refreshing multiple times

exists in `main` although it is more noticeable in this branch (although none of my debug statements triggered so maybe I need to optimize the `.vue` file somehow?). The easiest way to replicate the behavior is to create a spectral selection in cubeviz, then using the `remove` subset mode, remove a section from the subset. Before you complete you selection however, click and drag one end of the selection brush and wait, then continue that action until a considerable delay appears.

**Comment by pllim** [comment]
`KeyError: 'ComponentID not found or not unique: DATA'` means loading failed for one reason or another. I'll have to see if it is related or not, probably not but I cannot prove that right now.

**Comment by pllim** [comment]
You can ignore the dev failure: #2165

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue [hunk 1]
```diff
@@ -45,44 +45,29 @@
...
           :label="item.name"
           v-model.number="item.value"
           type="number"
         ></v-text-field>
       </v-row>
+    </v-row>
 
       <v-row justify="end" no-gutters>
-        <v-btn color="primary" text @click="update_subset">Update</v-btn>
+        <v-btn color="primary" text @click="update_subset" :disabled="!is_editable">Update</v-btn>
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:70]: should the actual inputs be disabled as well (if editing is being deferred)?

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue [hunk 2]
```diff
@@ -45,44 +45,29 @@
       </v-expansion-panels>
     </v-row>
 
-    <!-- Composite region cannot be edited, so just grab first element. -->
-    <div v-if="is_editable">
-      <v-row v-for="(item, index2) in subset_definitions[0]"
+    <!-- Show all subregions of a subset, including Glue state and subset type. -->
+    <v-row v-for="(region, index) in subset_definitions"
+    class="pt-0 pb-0 mt-0 mb-0" align=center>
```
Comment (kecnry) [inline jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:50]: what are all the `pt-0 pb-0 mt-0 mb-0` classes intended to accomplish?  Can these be simplified to get constant gutters (the inputs seem to extend all the way to the edge whereas the "subset type" and "glue state" rows do not) and perhaps use horizontal lines to delineate between entries?

**Review by kecnry — COMMENTED** [review]
Can any of this logic be moved up into `get_subsets`?  It's nice to remove a lot of the duplicated logic that used to be here, but it seems to have been replaced with even more lines than before.

What follow-up steps are next?  I'd still really like to see live-updating (instead of the update button) - do you think that will be feasible with this setup?

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue (hunk 2 above)
Comment (javerbukh) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:50]: Was trying different approaches and this one seemed to get me the closest to what I wanted, happy to change it! Can you direct me to resources for using gutters in the way you're describing? Or somewhere else in our code?

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue (hunk 1 above)
Comment (javerbukh) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:70]: I can try that and see how it looks.

**Comment by javerbukh** [comment]
@kecnry I could see the subset definition being moved to `get_subsets` but afaik there isn't a great reason for that. So far, only the Subset Plugin uses the front-end-friendly subset definition. Were there other sections you had in mind?

Live updating will most likely not be possible with this implementation considering the only way to update composite subsets (from what I've experimented with so far) is to create a copy with the updated values and then overwrite the subset with that copy. I plan on working on updating composite subsets as the follow-up work for this. I can absolutely give live updating a try in the next PR but I am not optimistic about it working with how subsets behave currently.

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue (hunk 2 above)
Comment (kecnry) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:50]: Maybe see https://jdaviz.readthedocs.io/en/latest/dev/ui_style_guide.html and feel free to update if you need something that isn't covered there?

**Review by duytnguyendtn — APPROVED** [review]
Code looks sensible to me! Considering the massive complications that came with this effort, it's great to actually have this feature working. Thanks, Jesse! I have a few comments on the UI, specifically when popped out:

In my default popout window, the boxes for the lower and upper bound collide with one another because the UI is trying to put them side-by-side. This makes it difficult to hit the increment buttons for the lower bound:
image

In addition, when I stretch the popout window, it reveals the elements are trying to be put in the same row, which can look pretty funky:
image

I think some columns and row definitions would help space things out a bit. I'm not sure how much this PR wants to go into the UI, but I wanted to present these as findings. I'll approve and leave it up to you whether you'd like to address. Thanks again!

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue (hunk 2 above)
Comment (javerbukh) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:50]: Removed the classes and have been trying all kinds of alignments but I cannot get the UI elements to stretch horizontally across the plugin even if the width is changed. I looked at similar plugin `.vue` files and I cannot see what I'm doing wrong. `guassian_smooth.vue` for example uses a `<v-text-field>` inside a `<v-row>` and that seems to be sufficient. Is it because I am using a `<v-row>` inside of another `<v-row>` that I am not seeing the same behavior?

Comment (kecnry) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:50]: It's possible - can you avoid nesting rows?  It would be nice to keep everything to just individual rows (and even avoid columns, unless absolutely necessary).

**Comment by javerbukh** [comment]
Here is what the layout looks like now:

image

**Review by kecnry — COMMENTED** [review]
Seems to work well in specviz and imviz - just have one comment and one question to clarify and then I think this will be good to get in and iterate further as needed.  Thanks!

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue [hunk 3]
```diff
@@ -45,44 +45,26 @@
...
-    <div v-if="is_editable">
-      <v-row v-for="(item, index2) in subset_definitions[0]"
-       class="pt-0 pb-0 mt-0 mb-0">
+    <!-- Show all subregions of a subset, including Glue state and subset type. -->
+    <div v-for="(region, index) in subset_definitions">
+      <v-row no-gutters>
+          <v-col>Subset type: {{ subset_types[index] }}</v-col>
+      </v-row>
+      <v-row no-gutters>
+          <v-col>Glue state: {{ glue_state_types[index] }}</v-col>
```
[the remark this answers is not in the document]
Comment (javerbukh) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:54]: Agreed about too technical but they are key to knowing which region is being modified: the square region taking the inverse or the square region in the corner? I'm sure there is a better way to present that information though so happy to iterate!

File: jdaviz/tests/test_subsets.py [hunk 4]
```diff
@@ -285,31 +284,32 @@ def test_disjoint_spectral_subset(cubeviz_helper, spectral_cube_wcs):
...
-    subsets = cubeviz_helper.app.get_subsets_from_viewer('spectrum-viewer')
-    reg = subsets.get('Subset 1')
+    reg = cubeviz_helper.app.get_subsets('Subset 1')
     assert_quantity_allclose(reg[1].lower, 30.0*u.Hz)  # Still the old value
 
     # See, never happened.
     subset_plugin.subset_selected = "Create New"
     subset_plugin.subset_selected = "Subset 1"
-    assert subset_plugin._get_value_from_subset_definition(0, "Lower bound", "value") == 30
+    assert subset_plugin._get_value_from_subset_definition(0, "Lower bound", "value") == 5
```
[the remark this answers is not in the document]
Comment (javerbukh) [reply jdaviz/tests/test_subsets.py:312]: Yes it's a re-ordering of the list. I can investigate getting that line (301) to work in the follow-up PR.

File: jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue (hunk 3 above)
[the remark this answers is not in the document]
Comment (kecnry) [reply jdaviz/configs/default/plugins/subset_plugin/subset_plugin.vue:54]: Right, I'm just wondering if human-friendly names (square, circle, ellipse, range) and then icons matching the edit subset dropdown would help make it easier for users... but that can be done later.

**Review by kecnry — APPROVED** [review]
Needs a change log, but otherwise looks ready to merge to me!

**Comment by javerbukh** [comment]
Thank you for the reviews! Merging now.
