### PR TITLE
Fix data menu cutoff in smaller viewers

### LINKED ISSUE #2551: BUG: Data menu cuts off, unable to select data at bottom
In a notebook, I am trying to load 4 different images, one on each viewer. So I have 4 viewers (1 default and 3 more added by hand). The data menu cuts off and refuses to let me pick the 4th image for display. I have to move the viewer of interest to a config where the whole data menu would show first, load the data, and then move the viewer back where I originally wanted it.

Screenshot 2023-11-01 182956

[🐱](https://jira.stsci.edu/browse/JDAT-3951)

### PR DESCRIPTION
**Pull request by haticekaratay**
### Description

This pull request fixes the issue of the cut-off data menu in smaller viewers when the list is longer.

https://github.com/spacetelescope/jdaviz/assets/66814693/96b50038-ff37-490f-b5a4-2296c44cfe0d

Fixes #2551 

### Change log entry

- [ ] Is a change log needed? If yes, is it added to `CHANGES.rst`? If you want to avoid merge conflicts,
  list the proposed change log here for review and add to `CHANGES.rst` before merge. If no, maintainer
  should add a `no-changelog-entry-needed` label.

### Checklist for package maintainer(s)

This checklist is meant to remind the package maintainer(s) who will review this pull request of some common things to look for. This list is not exhaustive.

- [ ] Are two approvals required? Branch protection rule does not check for the second approval. If a second approval is not necessary, please apply the `trivial` label.
- [ ] Do the proposed changes actually accomplish desired goals? Also manually run the affected example notebooks, if necessary.
- [ ] Do the proposed changes follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are tests added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Are docs added/updated as required? If so, do they follow the [STScI Style Guides](https://github.com/spacetelescope/style-guides)?
- [ ] Did the CI pass? If not, are the failures related?
- [ ] Is a milestone set? Set this to bugfix milestone if this is a bug fix and needs to be released ASAP; otherwise, set this to the next major release milestone.
- [ ] After merge, any internal documentations need updating (e.g., JIRA, Innerspace)?

### CODE REVIEW

**Comment by kecnry** [comment]
This seems to work well in some cases, but is also setting a fixed height that isn't always all used, and then still cannot reach bottom entries if the viewer height is smaller than the prescribed 200px height.

Screen Shot 2023-12-21 at 1 08 14 PM
Screen Shot 2023-12-21 at 1 08 20 PM


https://github.com/spacetelescope/jdaviz/assets/877591/8a0cdaca-1f5b-4d90-ab8d-7deda280ce23

File: jdaviz/components/viewer_data_select.vue [hunk 1]
```diff
@@ -107,6 +108,7 @@
         </div>
       </v-list>
     </v-menu>
+    <div ref="placeholder" :id="'target-' + viewer.id"></div>
```
Comment (kecnry) [inline jdaviz/components/viewer_data_select.vue:111]: is this ref ever used (I don't see anywhere in the final diff) or just referred to by target?

File: jdaviz/components/viewer_data_select.vue [hunk 2]
```diff
@@ -142,7 +144,33 @@ module.exports = {
...
+    while (element["tagName"] !== "BODY") {
+      if (["auto", "scroll"].includes(window.getComputedStyle(element).overflowY)) {
+        element.removeEventListener("scroll", this.onScroll);
+      }
+      element = element.parentElement;
+    }
+  },
   methods: {
+    onScroll(e) {
+      const dataMenuHeight = document.getElementById("menu-button").parentElement.getBoundingClientRect().height
```
Comment (kecnry) [inline jdaviz/components/viewer_data_select.vue:167]: I'm surprised that this doesn't need viewer id as well.... is that just because we currently hardcode the heights of the menus (and therefore they're all the same)?

**Review by kecnry — COMMENTED** [review]
There is a _very slight_ jitter during scroll and the data-menu can appear above the jupyter notebook interface, but I think those are small prices to pay for the benefits that this brings.... and all in a pretty lightweight and clean solution, thanks!

File: jdaviz/components/viewer_data_select.vue (hunk 1 above)
Comment (haticekaratay) [reply jdaviz/components/viewer_data_select.vue:111]: Good catch, and thank you for pointing that out. Initially, my intention was to implement this feature in a Vue-centric way, and the ref on the div was a part of that approach. I will remove the redundant reference in the upcoming commit.

File: jdaviz/components/viewer_data_select.vue (hunk 2 above)
Comment (haticekaratay) [reply jdaviz/components/viewer_data_select.vue:167]: Absolutely right, the use of a single ID across all viewers stems from their menus having a uniform hardcoded height of 42 px. Initially, I considered directly using the value, but opted for a slightly less coupled approach :)

Comment (kecnry) [reply jdaviz/components/viewer_data_select.vue:167]: ok, technically there are still multiple elements with this same ID, and it probably just grabs the first one (right?), but I think that's fine for now since we keep the same height.  Might just be worth a comment in-line (either here or where the id is set) in case we ever have different heights per-menu.  Or if it's just as easy to append the viewer id in both places, then that is a little more future-proofed.

**Review by kecnry — APPROVED** [review]

**Review by rosteen — APPROVED** [review]
Seems to work well for me, thanks!
